# -*- coding: utf-8 -*-
"""logic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RWB8dnTlQgxyjV9FlTR5IJ5Lu-C6AYck
"""

# Playing pegs' choice of colors

# Red, Orange, Yellow, Green, Blue, Purple, Brown, White
color_map = {
  "R" : "🔴",
  "O" : "🟠",
  "Y" : "🟡",
  "G" : "🟢",
  "B" : "🔵",
  "P" : "🟣",
  "N" : "🟤",
  "W" : "⚪",
}

# White, Red
feedback_map = {
  "W" : "⚪",
  "R" : "🔴",
}

secret = []
feedback = []
max_attempt = 7
game_size = 4

def display(lst):
  print()
  for i in lst:
    print(i, end=" ")

def displayFeedback(lst):
  print(end="  ")
  for i in lst:
    print(i, end=" ")

import random

def generateSecret(color_map, slots=4, repeats=False):
  # Create a random list according to the number of slots from choices as per the repeats flag
  global secret
  if repeats:
    secret = random.choices(list(color_map.values()), k=slots)
  else:
    secret = random.sample(list(color_map.values()), k=slots)

  display(secret)

def displayInput(user_input):
    # Remove spaces and convert to uppercase
    user_input = user_input.replace(" ", "").upper()

    if len(user_input) != 4:
        print("Invalid size")
        return -1

    lst = []

    for c in user_input:
        if c not in color_map:
            print(f"Invalid color code: {c}")
            return -1
        lst.append(color_map[c])

    display(lst)
    return validateInput(user_input)

def validateInput(user_input):
  # compare aganist the secret and build feedback - white for color matches only, red for color and place matches
  feedback = []
  secret_copy = secret[:]
  guess_copy = [color_map[c] for c in user_input]

  for i in range(len(user_input)):
    if guess_copy[i] == secret_copy[i]:
        feedback.append(feedback_map["R"])
        secret_copy[i] = None      # Mark as used
        guess_copy[i] = None

  for color in guess_copy:
      if color is not None and color in secret_copy:
          feedback.append(feedback_map["W"])
          secret_copy[secret_copy.index(color)] = None

  if countR(feedback) == game_size:
    return 1
  # Randomize the feedback
  random.shuffle(feedback)
  displayFeedback(feedback)

# Count # of R in teh list
def countR(lst):
  count = 0
  for i in lst:
    if i == "🔴":
      count += 1
  return count

generateSecret(color_map, 4, False)

def play():
  counter = 0
  revealed = 0
  while revealed != 1:
    counter+=1
    if counter <= max_attempt:
      revealed = displayInput(input())
      if revealed == -1:
        counter -= 1
        continue
      elif revealed == 1:
        print("   \033[1;32mY O U   W O N !\033[0m")
    else:
      print("   \033[1;31mY O U   L O S T 😞\033[0m")
      revealed = True

play()

