# -*- coding: utf-8 -*-
"""logic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RWB8dnTlQgxyjV9FlTR5IJ5Lu-C6AYck
"""

# Playing pegs' choice of colors

# Red, Orange, Yellow, Green, Blue, Purple, Brown, White
color_map = {
  "R" : "🔴",
  "O" : "🟠",
  "Y" : "🟡",
  "G" : "🟢",
  "B" : "🔵",
  "P" : "🟣",
  "N" : "🟤",
  "W" : "⚪",
}

# White, Red
feedback_map = {
  "W" : "⚪",
  "R" : "🔴",
}

secret = []
feedback = []

def display(lst):
  print()
  for i in lst:
    print(i, end=" ")

def displayFeedback(lst):
  print(end="  ")
  for i in lst:
    print(i, end=" ")

import random

def generateSecret(color_map, slots=4, repeats=False):
  # Create a random list according to the number of slots from choices as per the repeats flag
  global secret
  if repeats:
    secret = random.choices(list(color_map.values()), k=slots)
  else:
    secret = random.sample(list(color_map.values()), k=slots)

  display(secret)

def displayInput(user_input):
    # Remove spaces and convert to uppercase
    user_input = user_input.replace(" ", "").upper()

    if len(user_input) != 4:
        print("Invalid size")
        return

    lst = []

    for c in user_input:
        if c not in color_map:
            print(f"Invalid color code: {c}")
            return
        lst.append(color_map[c])

    display(lst)
    validateInput(user_input)

def validateInput(user_input):
  # compare aganist the secret and build feedback - white for color matches only, red for color and place matches
  feedback = []
  secret_copy = secret[:]
  guess_copy = [color_map[c] for c in user_input]

  for i in range(len(user_input)):
    if guess_copy[i] == secret_copy[i]:
        feedback.append(feedback_map["R"])
        secret_copy[i] = None      # Mark as used
        guess_copy[i] = None

  for color in guess_copy:
      if color is not None and color in secret_copy:
          feedback.append(feedback_map["W"])
          secret_copy[secret_copy.index(color)] = None

  # Randomize the feedback
  random.shuffle(feedback)
  displayFeedback(feedback)

generateSecret(color_map, 4, False)

displayInput(input())

displayInput(input())

!git status

