# -*- coding: utf-8 -*-
"""logic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RWB8dnTlQgxyjV9FlTR5IJ5Lu-C6AYck
"""

# Playing pegs' choice of colors

# Red, Orange, Yellow, Green, Blue, Purple, Brown, White
color_map = {
  "R" : "🔴",
  "O" : "🟠",
  "Y" : "🟡",
  "G" : "🟢",
  "B" : "🔵",
  "P" : "🟣",
  "N" : "🟤",
  "W" : "⚪",
}

def display(lst):
  for i in lst:
    print(i, end=" ")
  print()

import random

def generateSecret(color_map, slots=4, repeats=False):
  # Create a random list according to the number of slots from choices as per the repeats flag
  if repeats:
    secret = random.choices(list(color_map.values()), k=slots)
  else:
    secret = random.sample(list(color_map.values()), k=slots)
  display(secret)

generateSecret(color_map, 4, False)

def displayInput(user_input):
    # Remove spaces and convert to uppercase
    user_input = user_input.replace(" ", "").upper()

    if len(user_input) != 4:
        print("Invalid size")
        return

    lst = []

    for c in user_input:
        if c not in color_map:
            print(f"Invalid color code: {c}")
            return
        lst.append(color_map[c])

    display(lst)

displayInput(input())

